version: '3.8'

services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    ports:
      - '8053:53/tcp'
      - '8053:53/udp'
      - '80:80/tcp'
      - '80:80/udp'
      - '3000:3000/tcp'
      - '853:853/tcp'
      - '853:853/udp'
      - '5443:5443/tcp'
      - '5443:5443/udp'
      - '943:943/tcp'
      - '943:943/udp'
      - '9000:9000/tcp'
      - '9000:9000/udp'
    volumes:
      - './adguard_config:/opt/adguardhome/conf'
      - './adguard_data:/opt/adguardhome/work'
    restart: unless-stopped

  db:
    image: mariadb:10.6
    restart: always
    command:
      - '--transaction-isolation=READ-COMMITTED'
      - '--log-bin=binlog'
      - '--binlog-format=ROW'
    volumes:
      - 'db:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=sml4ever12345
      - MYSQL_PASSWORD=sml4ever12345
      - MYSQL_DATABASE=vmadmin
      - MYSQL_USER=vmadmin

  app:
    image: nextcloud
    restart: always
    ports:
      - '8080:80'
    depends_on:
      - db
    volumes:
      - 'nextcloud:/var/www/html'
    environment:
      - MYSQL_PASSWORD=sml4ever12345
      - MYSQL_DATABASE=vmadmin
      - MYSQL_USER=vmadmin
      - MYSQL_HOST=db

  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock' # Optional, only if you want docker integration
      - './homarr/configs:/app/data/configs'
      - './homarr/icons:/app/public/icons'
      - './homarr/data:/data'
    ports:
      - '7575:7575'

volumes:
  prom_data:
  db:
  nextcloud:
